server:
  port: 8002
  servlet:
    context-path: /module/product/api

spring:
  application:
    name: intelligent-module-product

sourceflag:
  agile:
    logger:
      enable: true
      local-log-recorder-config:
        enable: true
        record-levels: error
    idempotent:
      enable: true
      message: "操作频繁，请稍后再试"
    limiter:
      enable: true
      message: "接口限流，请稍后再试"
    distribute-locks:
      enable: true
      message: "系统繁忙，请稍后再试"
    database:
      enable: true
      show-sql: true
      ddl-auto: update
      delete-column: false
    sensitive:
      enable: true
      load-type: other
      placeholder: "***"

application:
  components:
    swagger:
      enable: true
    caching:
      enable: true
      entry-ttl: 3600s
      cache-type: redis
      cache-name-suffix: ${application.name:}