server:
  port: 8888

spring:
  application:
    name: intelligent-gateway

  cloud:
    gateway:
      default-filters:
        # 令牌中继，会在请求头中添加 token 向下游传递
        - TokenRelay=
        - DedupeResponseHeader=Access-Control-Allow-Origin
      routes:
        - id: intelligent-core-api-route
          uri: lb://intelligent-core-api
          predicates:
            - Path=/core/api/**

        - id: intelligent-module-crm-route
          uri: lb://intelligent-module-crm
          predicates:
            - Path=/crm/api/**

        - id: intelligent-module-product-route
          uri: lb://intelligent-module-product
          predicates:
            - Path=/product/api/**

        - id: intelligent-module-stock-route
          uri: lb://intelligent-module-stock
          predicates:
            - Path=/stock/api/**