server:
  port: 6666

spring:
  application:
    name: intelligent-oauth-server

sourceflag:
  agile:
    database:
      enable: true
      show-sql: true
      ddl-auto: update
      delete-column: false

logging:
  level:
    org.springframework.security: trace

oauth2:
  issuer-uri: http://localhost:${server.port}
  cors:
    allowed-origins: "*"