server:
  port: 9000
  servlet:
    context-path: /core/api

spring:
  application:
    name: intelligent-core-api

sourceflag:
  agile:
    logger:
      enable: true
      local-log-recorder-config:
        enable: true
        record-levels: error
    idempotent:
      enable: true
      message: "操作频繁，请稍后再试"
    limiter:
      enable: true
      message: "接口限流，请稍后再试"
    distribute-locks:
      enable: true
      message: "系统繁忙，请稍后再试"
    database:
      enable: true
      show-sql: true
      ddl-auto: update
      delete-column: false